name: ID application
description: Fill in this for to get assigned an indicator ID
title: '[New ID]' 
labels: new-ID
assignees: anders-kolstad
body:
  - type: markdown
    attributes:
      value: |
        Indicator IDs are assigned by ecRxiv and used to uniquely identify indicators. Please see the wiki page for further description on the naming convention: https://github.com/NINAnor/ecRxiv/wiki#naming-convention 
  - type: input
    id: contact
    attributes:
      label: Contact Details
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: inputtext
    attributes:
      label: Describe the indicator.
      description: Describe shortly what the indicator is, for example by giving the commonly used indicator name and ecosystem it is related to. 
    validations:
      required: true
- type: textarea
    id: other
    attributes:
      label: Related indicators
      description: Are there any related indicators that this ID should be harmonised against?
    validations:
      required: false
- type: textarea
    id: sugg
    attributes:
      label: Add suggestions
      description: You can suggest your own ID here.
    validations:
      required: false
