name: FEEDBACK
description: Provide comments or feedback.
title: "[FEEDBACK]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for provideing feedback to ecRxiv!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: input?
    attributes:
      label: What's on your mind
      value: Add your feedback in this box. 
      description: If you are reporting a bug, please be as specific as possible.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: ID
    attributes:
      label: Indicator ID
      value: Write the indicator ID or name here
      description: ...if relevant
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: I confirm that I read and will adhere to the [code of conduct](https://github.com/NINAnor/ecRxiv/blob/main/docs/code_of_conduct.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
