name: Indicator review form
description: Start comprehensive review of an indicator found on ecRxiv
title: "[REVIEW]: "
labels: ["REVIEW"]
assignees:
  - anders-kolstad
body:
  - type: markdown
    attributes:
      value: |
        ## Review checklist
        
        Thank you for reviewing this indicator!

        Please go through the checklist below and tick the boxes that are fulfilled, and add comments as needed. 
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false     
  - type: input
    id: indicator_id
    attributes:
      label: Indicator ID
      description: Please enter the indicator ID for this review
      placeholder: e.g. NO_XXX_001
    validations:
      required: true


  - type: checkboxes
    id: conflict_of_interest
    attributes:
      label: Conflict of Interest
      options:
        - label: I confirm that I have NO conflict of interest that makes me unsuited to review this indicator. If I do have a conflict, I will declare them in the comment below.
          required: false

  - type: textarea
    id: CoI
    attributes:
      label: Comments
      placeholder: Describe potential conflice of interest here or leave blank is not relevant
    validations:
      required: false

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      options:
        - label: I confirm that I read and will adhere to the [code of conduct](https://github.com/NINAnor/ecRxiv/blob/main/docs/code_of_conduct.md)
          required: true


  - type: checkboxes
    id: authorship_checks
    attributes:
      label: Contribution and authorship
      options:
        - label: Does the author list seem appropriate and complete?

  - type: textarea
    id: authorship_comments
    attributes:
      placeholder: Add additional comments about authorship here
    validations:
      required: false

  - type: checkboxes
    id: metadata_checks
    attributes:
      label: Meta data
      options:
        - label: Does the metadata entered for the indicator seem correct, including ECT class and ecosystem type?

  - type: textarea
    id: metadata_comments
    attributes:
      placeholder: Add additional comments about metadata here
    validations:
      required: false

  - type: checkboxes
    id: summary_checks
    attributes:
      label: Common language summary
      options:
        - label: Is the common language summary concise and clear?

  - type: textarea
    id: summary_comments
    attributes:
      placeholder: Add additional comments about the summary here
    validations:
      required: false

  - type: checkboxes
    id: introduction_checks
    attributes:
      label: Introduction and conclusion
      options:
        - label: Is the introduction written so that it sums up the general method and usability of the indicator?

  - type: textarea
    id: introduction_comments
    attributes:
      placeholder: Add additional comments about introduction and conclusion here
    validations:
      required: false

  - type: checkboxes
    id: structure_checks
    attributes:
      label: Legibility and structure
      options:
        - label: Is the documentation written so that it is easy, or at least possible, to follow the arguments?
        - label: Is each header and sub-header populated with the appropriate text?

  - type: textarea
    id: structure_comments
    attributes:
      placeholder: Add additional comments about legibility and structure here
    validations:
      required: false

  - type: checkboxes
    id: visuals_checks
    attributes:
      label: Images, tables and figures
      options:
        - label: Does the documentation contain the appropriate amount of tables, figures and images?
        - label: Do the visuals have high enough quality?

  - type: textarea
    id: visuals_comments
    attributes:
      placeholder: Add additional comments about images, tables and figures here
    validations:
      required: false

  - type: checkboxes
    id: uncertainty_checks
    attributes:
      label: Statement of uncertainty and needs
      options:
        - label: Do the authors include a clear description of the different sources of uncertainty or errors for the indicator?

  - type: textarea
    id: uncertainty_comments
    attributes:
      placeholder: Add additional comments about uncertainty statement here
    validations:
      required: false

  - type: checkboxes
    id: validation_checks
    attributes:
      label: Validation
      options:
        - label: Does the documentation include some sort of validation for the precision of the indicator values?
        - label: Is this validation sufficient?

  - type: textarea
    id: validation_comments
    attributes:
      placeholder: Add additional comments about validation here
    validations:
      required: false

  - type: checkboxes
    id: relevance_checks
    attributes:
      label: Relevance
      options:
        - label: Does this indicator have relevance as an ecosystem condition indicator for the given ecosystems?

  - type: textarea
    id: relevance_comments
    attributes:
      placeholder: Add additional comments about relevance here
    validations:
      required: false

  - type: checkboxes
    id: reproducibility_checks
    attributes:
      label: Reproducibility
      options:
        - label: Is the documentation sufficient, or seem sufficient enough, to make the results entirely reproducible by the reviewers?

  - type: textarea
    id: reproducibility_comments
    attributes:
      placeholder: Add additional comments about reproducibility here
    validations:
      required: false

  - type: checkboxes
    id: references_checks
    attributes:
      label: References
      options:
        - label: Do the references seem appropriate?
        - label: Do important hyperlinks work?

  - type: textarea
    id: references_comments
    attributes:
      placeholder: Add additional comments about references here
    validations:
      required: false

  - type: textarea
    id: additional_comments
    attributes:
      label: Additional General Comments
      description: Add any additional comments, feedback, or concerns about the indicator
      placeholder: Enter your general comments here...
    validations:
      required: false