name: Indicator review form
description: Start comprehensive review of an indicator found on ecRxiv
title: "[REVIEW]: "
labels: ["REVIEW"]
assignees:
  - anders-kolstad
body:
  - type: markdown
    attributes:
      value: |
        ## Review checklist
        
        Thank you for reviewing this indicator!

        Please go through the checklist below and tick the boxes that are fulfilled, and add comments as needed. 
        
  - type: input
    id: indicator_id
    attributes:
      label: Indicator ID
      description: Please enter the indicator ID for this review
      placeholder: e.g. NO_XXX_001
    validations:
      required: true


  - type: checkboxes
    id: conflict_of_interest
    attributes:
      label: Conflict of Interest
      options:
        - label: I confirm that I have NO conflict of interest that makes me unsuited to review this indicator. If I do have a conflict, I will declare them in the comment below.
          required: false

  - type: textarea
    id: CoI
    attributes:
      label: Comments
      placeholder: Describe potential conflice of interest here or leave blank is not relevant
    validations:
      required: false

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      options:
        - label: I confirm that I read and will adhere to the [code of conduct](https://github.com/NINAnor/ecRxiv/blob/main/docs/code_of_conduct.md)
          required: true

  - type: checkboxes
    id: general_checks1
    attributes:
      label: Contribution and authorship
      options:
        - label: Does the author list seem appropriate and complete?

  - type: textarea
    id: ContributionComments
    attributes:
      label: Comments
      placeholder: Add additional comments here 
    validations:
      required: false

  - type: checkboxes
    id: general_checks
    attributes:
      label: Contribution and authorship:
      options:
        - label: "**Contribution and authorship:** Does the author list seem appropriate and complete?"
        - label: "**Meta data:** Does the metadata entered for the indicator seem correct, including ECT class and ecosystem type?"
        - label: "**Common language summary:** The common language summary is concise and clear."
        - label: "**Introduction and conclusion:** Is the introduction written so that it sums up the general method and usability of the indicator?"
        - label: "**Legibility and structure:** Is the documentation written so that it is easy, or at least possible, to follow the arguments? Is each header and sub-header populated with the appropriate text?"
        - label: "**Images, tables and figures:** Does the documentation contain the appropriate amount of tables, figures and images, and do these have high enough quality?"
        - label: "**A statement of uncertainty and needs:** Do the authors include a clear description of the different sources of uncertainty or errors for the indicator?"
        - label: "**Validation:** Does the documentation include some sort of validation for the precision of the indicator values, and is this validation sufficient?"
        - label: "**Relevance:** Do the reviewers judge that this indicator has relevance as an ecosystem condition indicator for the given ecosystems?"
        - label: "**Reproducibility:** Is the documentation sufficient, or seem sufficient enough, to make the results entirely reproducible by the reviewers?"
        - label: "**References:** Do the references seem appropriate and do important hyperlinks work?"

  - type: textarea
    id: additional_comments
    attributes:
      label: Additional Comments
      description: Add any additional comments, feedback, or concerns about the indicator
      placeholder: Enter your comments here...
    validations:
      required: false

  - type: textarea
    id: conflict_declaration
    attributes:
      label: Conflict of Interest Declaration
      description: If you have any conflicts of interest to declare, please describe them here
      placeholder: Describe any conflicts of interest...
    validations:
      required: false