name: Indicator selection criteria checklist
description: A checklist of ecosystem condition indicator selection criteria after Czúcz et al 2021 (https://doi.org/10.1016/j.ecolind.2021.108376) and Nybø and Evju 2017 (Fagsystem for fastsetting av god 
økologisk tilstand. Forslag fra et ekspertråd; ISBN 978-82-690860-0-3).
title: '[Selection criteria]: "indicatorID"'
labels: selection-checklist
assignees: anders-kolstad
body:
  - type: markdown
    attributes:
      value: |
        Please update the issue title with the indicator ID.
        Then click 'create'. Then you can go through the tick boxes one by one. 

        The checklist starts with the criteria from Czúcz et al.
  - type: input
    id: prid
    attributes:
      label: PR number
      description: If this checklist is applied on a indicator under review, please link to the PR
      placeholder: "#123"
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: I confirm that I read and will adhere to the [code of conduct](https://github.com/NINAnor/ecRxiv/blob/main/docs/code_of_conduct.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: coi
    attributes:
      label: Conflict of Interest
      description: I confirm that I have **no** conflict of interest that makes me unsuited to review this indicator. If not, I will declare my conflict of interest in a comment below.
      options:
        - label: I confirm that I have **no** conflict of interest
          required: false
  - type: input
    id: one
    attributes:
      label: Intrinsic relevance
      description: |
        Characteristics and metrics should reflect existing scientific understanding of ecosystem integrity, supported by the ecological literature.
    validations:
      required: true
    
  - type: input
    id: two
    attributes:
      label: Instrumental relevance
      description: |
        Characteristics and metrics should be related to the availability of ecosystem services (characteristics that provide most information about the highest number of services should be favoured).
    validations:
      required: true
        
  - type: input
    id: three
    attributes:
      label: Directional meaning
      description: |
        Characteristics and metrics need to have a potential for a consensual normative interpretation (it should be clear if a change is favourable or unfavourable).
    validations:
      required: true
    
  - type: input
    id: four
    attributes:
      label: Sensitivity to human influence
      description: |
        Characteristics and metrics should be responsive to known socio-ecological leverage points (key pressures, management options).
    validations:
      required: true

  - type: input
    id: five
    attributes:
      label: Framework conformity
      description: |
        Characteristics and metrics should be differentiated from other components of the SEEA ecosystem accounting framework.
    validations:
      required: true

  - type: input
    id: six
    attributes:
      label: Validity
      description: |
        Metrics need to represent the characteristics they address in a credible and unbiased way.
    validations:
      required: true
  
  - type: input
    id: seven
    attributes:
      label: Intrinsic relevance
      description: |
        Characteristics and metrics should reflect existing scientific understanding of ecosystem integrity, supported by the ecological literature.
    validations:
      required: true
  
  - type: input
    id: eight
    attributes:
      label: Reliability
      description: |
        Metrics need to be accurate, reliable, and reproducible, with potential sources of error explored and documented.
    validations:
      required: true
        
  - type: input
    id: nine
    attributes:
      label: Availability
      description: |
        Metrics covering the studied spatial and temporal extents with the required resolution need to be achievable in terms of the resources and time available.
    validations:
      required: true
  - type: input
    id: ten
    attributes:
      label: Simplicity
      description: |
        Metrics should be as simple as possible
    validations:
      required: true
  
  - type: input
    id: elleven
    attributes:
      label: Compatibility
      description: |
        The same characteristics should be measured with the same (compatible) metrics in the different ecosystem types and/or different ecosystem accounting areas (countries).
    validations:
      required: true
  
  - type: input
    id: twelve
    attributes:
      label: Comprehensiveness
      description: |
        The final set of metrics, as a whole, should cover all of the relevant characteristics of the ecosystem. This might not be possible to anwer when assessing individual indicators.
    validations:
      required: true
  
  - type: input
    id: thirteen
    attributes:
      label: Parsimony
      description: |
        The final set of metrics should be free of redundant (correlated) variables.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        The selection criteria in Nybø and Evju (2017) overlap considerably with the above. Here is the entire list for reference, and two points are made into seperate inputs text boxes below. These are in Norwegian.
        
        **Kriterier for valg av miljøindikatorer**
        
        Relevans og nytteverdi for brukere
        
        En miljøindikator bør:
        
        - gi et representativt bilde av miljøets tilstand, miljøpåvirkninger eller samfunnets respons
        - være enkel, lett å tolke og i stand til å vise trender over tid
        - respondere på endringer i miljøet og relaterte menneskelige aktiviteter
        - gi grunnlag for internasjonale sammenligninger
        - være relevant for det arealet som vurderes
        - ha en terskelverdi eller referanseverdi som den kan sammenlignes mot, slik at brukere kan vurdere betydningen av indikatorens verdi

        Analytisk forsvarlighet
        
        En miljøindikator bør:
        
        - være teoretisk godt fundert i tekniske og vitenskapelige termer
        - være basert på internasjonale standarder og internasjonal konsensus om gyldighet
        - være egnet til å kobles mot økonomiske modeller, prognoser og informasjonssystemer
        
        Målbarhet
        
        Data som trengs for å støtte indikatoren, bør: 
        
        - være lett tilgjengelig eller kunne gjøres tilgjengelig på en kostnadseffektiv måte
        - være godt dokumentert og av kjent kvalitet
        - oppdateres jevnlig i samsvar med utarbeidede prosedyrer


  - type: input
    id: fourteen
    attributes:
      label: Skaleringverdi
      description: |
        Ha en terskelverdi eller referanseverdi som den kan sammenlignes mot, slik at brukere kan vurdere betydningen av indikatorens verdi.
        Hvordan vurderes kvaliteten eller gyldigheten til skaleringsverdiene (referanseverdier, grenseverdier, osv.)?
    validations:
      required: true

  - type: input
    id: fifteen
    attributes:
      label: Oppdatering
      description: |
        Oppdateres jevnlig i samsvar med utarbeidede prosedyrer.
    validations:
      required: true
      
  - type: input
    id: final
    attributes:
      label: Additional comments
    validations:
      required: true
        
        
