all_args <- commandArgs(trailingOnly = FALSE)
script_arg <- grep("^--file=", all_args, value = TRUE)
script_path <- sub("^--file=", "", script_arg[[1]])
root <- normalizePath(file.path(dirname(script_path), ".."), mustWork = TRUE)
Sys.setenv(NO_GJEN_002_ROOT = root)
source(file.path(root, "R", "pipeline_common.R"))
source(file.path(root, "R", "calculate_indicator.R"))

stopifnot(identical(scale_encroachment(0, 0, 10), 1))
stopifnot(identical(scale_encroachment(10, 0, 10), 0))
stopifnot(is.na(scale_encroachment(1, 2, 2)))
stopifnot(abs(weighted_result(c(1, 0), c(3, 1))[["value"]] - 0.75) < 1e-12)
stopifnot(weighted_result(c(NA, 1), c(2, 2))[["n"]] == 1)
message("NO_GJEN_002 unit smoke tests passed")
